### PR TITLE
Updated Reporting

### PR DESCRIPTION
**Pull request by n03lx**
Added capability for reporting with PowerShell version 1 and 2

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Hey, thanks for sending this over!  I think my only question at first is the setting the report variable to accept the value by pipeline.  I realize that it isn't in it right now, but I think the IP address might be a better candidate for accepting the value by pipeline.

**Comment by ChrisTruncer** [comment]
Thoughts on changing it to that?

**Comment by ChrisTruncer** [comment]
Closing since I haven't heard back

**Comment by n03lx** [comment]
My bad... never check this thing. I can look into changing that.

**Pull request closed without merging**
