### PR TITLE
Dockerfile Creation

### PR DESCRIPTION
**Pull request by piesecurity**
After looking at the list of dependences this project seemed like a good candidate for a docker image. The dockerfile has been added to the setup directory and an automated build can be downloaded from dockerhub

$docker pull piesecurity/egress-assess

All of the client protocols work while running inside of docker. Most server protocols work except ICMP and FTP. I haven't quite figured those two out yet.

Overall, great project and hopefully containerization assists in specific use cases.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
I'm trying to decide if this is something that should be merged in right now, or after you've found the issue with ICMP and FTP.  Thoughts?

**Comment by piesecurity** [comment]
Sure, I found workaround for both. Although FTP did involve a slight change to overall server function.

The server will now run in passive mode. Predictable ports of 60000-60100 makes the setup easier and Urllib is called to assist with populating the masquerade IP. There are dozens of ways to do that if you prefer another way. Overall, the change from active to passive might not be a bad idea anyways. The client will initiate all egress connections. 

ICMP requires an iptables workaround after a server container is build. It is a quick note I added into the Dockerfile. I haven't found a way for Docker to forward ICMP inside the docker run command.

iptables -t nat -A PREROUTING -p ICMP -i <internet_interface> -j DNAT --to-destination <dockerContainerIP>

**Comment by ChrisTruncer** [comment]
I like the idea, the only thing is I don't want to force the FTP server to have to use the Public IP address.  I'd rather have it defer to it's current configuration where it tried to figure out it's current IP, and then maybe if you specify an IP from the command line, it uses that instead.

You'd need to change line 50 (of the original file), and do some sort of a detection if the --ip flag is set, then use it, otherwise leave it at the default setting.  Other than that, I'm fine with the high port range and everything else.

**Comment by piesecurity** [comment]
That makes perfect sense. How does that look? In testing, I didn't need to change the binding where the server class was initiated. It defaults properly  when --ip is not defined. It worked on the local LAN and cross the Internet through a couple of NATs

**Comment by ChrisTruncer** [comment]
OK, that looks good to me.  I would have thought you would have to put the IP in the FTPServer information, but if it works with the masquerade_address, then awesome.

**Comment by ChrisTruncer** [comment]
merged

**Pull request merged**
